<?php
$idUser = $_GET['var'];
    include 'seguridad.php';
	include 'seguridadAdminPanel.php';
	include	'conexion.php';
	echo "<link rel='stylesheet' href='css/main.css'/>";
	echo "<link rel='stylesheet' href='css/adminEnlistar-Editar-Detalle.css'/>"; 
	#	<!--CONTENEDOR-->	
		echo "<div id='contenedor'>";
			#<!--CABERERA-->
			echo "<div id='cabecera'>";
			echo "<div id='logo'>";
			include ("logo.php");
			echo "</div>";
			echo "<div id='menu'>";
			include ("menu.php");
			echo "</div>";
		echo "</div>";
			#<!--FIN CABECERA-->
			$query = "select * from usuario where ID_Usuario='$idUser'";
			$result = mysql_query($query);
			echo "<div id='panel'>";
			while ($row = mysql_fetch_row($result)) {
				do{				
				echo "<table id='tablaLista'>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Nombre:";
				echo "</td>";
				echo "<td>";
				echo "$row[1]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Rut: ";
				echo "</td>";
				echo "<td>";
				echo "$row[2]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Edad: ";
				echo "</td>";
				echo "<td>";
				echo "$row[3]";
				echo "</td>";
				echo "</tr>";
				echo "<td class='izq'>";
				echo "Sexo: ";
				echo "</td>";
				echo "<td>";
				echo "$row[13]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Direccion: ";
				echo "</td>";
				echo "<td>";
				echo "$row[4]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Ciudad: ";
				echo "</td>";
				echo "<td>";
				echo "$row[5]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Fono: ";
				echo "</td>";
				echo "<td>";
				echo "$row[6]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Movil: ";
				echo "</td>";
				echo "<td>";
				echo "$row[7]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Estado Civil: ";
				echo "</td>";
				echo "<td>";
				echo "$row[8]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Local de votacion: ";
				echo "</td>";
				echo "<td>";
				echo "$row[9]";
				echo "</td>";
				echo "</tr>";
				$tipoUsuario = "";
				if($row[10] == 1){
					$tipoUsuario = "Administrador";
				}elseif($row[10] == 2){
					$tipoUsuario = "Votante";
				}else{
					$tipoUsuario = "Usuario";
				}
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Tipo de usuario: ";
				echo "</td>";
				echo "<td>";
				echo "$tipoUsuario";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Usuario: ";
				echo "</td>";
				echo "<td>";
				echo "$row[11]";
				echo "</td>";
				echo "</tr>";
				echo "<tr>";
				echo "<td class='izq'>";
				echo "Password: ";
				echo "</td>";
				echo "<td>";
				echo "$row[12]";
				echo "</td>";
				echo "</tr>";
				echo "</table>";
				echo "<form method='post' action='editarUsuario.php'>";
				echo "<input type='hidden' name='txtIdUsuario' value='$row[0]'>";
				echo "<input type='submit' value='Editar usuario' name='submit' id='submit' class='submit'>";
				echo "</form>";
				}while($row = mysql_fetch_array($result));
			}
			echo "</div>";
			echo "<div id='pie'>";
			include ("pie.php");
			echo "</div>";			
		echo "</div>";
		#<!--FIN CONTENEDOR-->
?>